### ISSUE TITLE
cargo run --bin triangle: failed to create Vulkan instance: InitializationFailed

### ISSUE THREAD

**Issue by bgalvao** [vulkano-rs/vulkano-examples#25]
For several times I tried getting started with vulkano. Here's what I have to report.
- I have an NVidia driver installed from the [`graphics-drivers`](https://launchpad.net/~graphics-drivers/+archive/ubuntu/ppa) ppa (if that makes a difference)
- I've done `sudo apt install libvulkan1 libvulkan-dev`
- I've also installed [LunarG](https://www.lunarg.com/), just in case.

After all this I'm still getting
```
bgalvao@buzzie:~/repos/vulkano-examples$ cargo run --bin triangle
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/triangle`
thread 'main' panicked at 'failed to create Vulkan instance: InitializationFailed', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by nicmr** [comment]
Hi bgalvao!
I think the default nvidia driver doesn't support vulkan as is - you might have to install the corresponding vulkan driver from [here](https://developer.nvidia.com/vulkan-driver). It would be great if somebody could confirm this, as I have an amd gpu.

I think it's possible to run mesa alongside the proprietary proprietary nvidia driver so if that's an option for you, I suggest installing mesa and the corresponding [mesa vulkan drivers](https://packages.ubuntu.com/bionic/mesa-vulkan-drivers).
I don't know how you could tell cargo to run your vulkan projects with mesa instead of nvidia when both are installed though.

Mesa is working perfectly for me.

**Comment by bgalvao** [comment]
Hi @nicmr ! thanks, I tried it today on my netbook (integrated gpu) following your / [gfx-rs instructions](https://github.com/gfx-rs/gfx/blob/master/info/getting_started.md). Indeed the mesa drivers worked just fine :)
